[feat] 닉네임 중복 검사 로직 구현
JaManChu/backend pull request #100
Opened 2024-10-14 16:40 UTC by DlrkdhsOff

- [ ] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `[feat] PR을 등록한다.` 
- [ ] 💯 테스트는 잘 통과했나요?
- [ ] 🏗️ 빌드는 성공했나요?
- [ ] 🧹 불필요한 코드는 제거했나요?
- [ ] 💭 이슈는 등록했나요?
- [ ] 🏷️ 라벨은 등록했나요?

## 작업 내용
- 닉네임 중복 검사하는 로직을 구현 및 회원가입, 회원 정보 수정에서 닉네임 중복 검사 로직을 삭제 했습니다.

- 구현한 내용 요약
   - 구현한 클래스
      - MissingNicknameException
         - 클라인언트 측으로 부터 전달 받은 닉네임 값이 null 일 경우 발생하는 예외 처리 클래스
         
   - 수정한 클래스
      - AuthController
         - 닉네임 중복 검사 요청을 받을 메서드 구현
      - AuthService & AuthServiceImpl
         - 닉네임 중복 검사 로직 구현
            - 사용가능 한 닉네임 입니다.
            - 이미 사용중인 닉네임 입니다.
      - UserAccessHandler
         - existsByNickname
            - 사용가능한 닉네임 : NICKNAME_AVAILABLE
            - 사용중인 닉네임 : NICKNAME_ALREADY_IN_USE    
      - ResutlCode
         - 닉네임 사용가능 여부에 따른 상태 코드 추가
      - ExceptionStatus
         - 닉네임 중복검사 실패 상태 코드 추가
      - UserServiceImpl
         - 회원가입 시 닉네임 중복 검사 로직 삭제
         - 회원 정보 수정시 닉네임 중복 검사 로직 삭제

    - 삭제한 클래스
       - DuplicatedNicknameException
## 스크린샷

## 주의사항

Closes #94

2024-10-14 16:48 UTC, heesane requested changes
확인했습니다. 코멘트 확인해주세요.

2024-10-14 16:48 UTC, heesane commented on jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
> -      throw new DuplicatedNicknameException();
예외인 경우 예외처리가 아니라 정상 응답을 보내는 건가요?

2024-10-14 16:48 UTC, heesane commented on jamanchu/src/main/java/com/recipe/jamanchu/controller/AuthController.java
> +    }
required가 false로 설정하신 이유가 있나요?

2024-10-14 16:48 UTC, heesane commented on jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
> +  NICKNAME_ALREADY_IN_USE(HttpStatus.CONFLICT, "이미 사용 중인 닉내임 입니다."),
이 부분은 왜 이렇게 하시는거죠?
ResultCode에는 초기에 성공에 대한 케이스만 존재했는데 중복이나 데이터가 없는 경우에는 예외로 처리해야 하는거 아닌가요?

2024-10-14 16:48 UTC, heesane commented on jamanchu/src/main/java/com/recipe/jamanchu/service/AuthService.java
>  }
음 ResultCode로 반환하는 이유가 있나요? 비즈니스 로직에서 ResultResponse로 변환해서 반환해도 될텐데요.
Controller와 Service의 차이에 대해서 알아보시면 좋을 것같습니다.

2024-10-14 17:13 UTC, DlrkdhsOff commented on jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
> +  NICKNAME_ALREADY_IN_USE(HttpStatus.CONFLICT, "이미 사용 중인 닉내임 입니다."),
이 부분은 원래 api 명세서 기준대로 하다보니 이부분은 예외를 처리 하지 않는 방식이여서 이렇게 구현을 했습니다.

2024-10-14 17:14 UTC, DlrkdhsOff commented on jamanchu/src/main/java/com/recipe/jamanchu/service/AuthService.java
>  }
넵 바로 수정하도록 하겠습니다

2024-10-14 17:15 UTC, DlrkdhsOff commented on jamanchu/src/main/java/com/recipe/jamanchu/component/UserAccessHandler.java
> -      throw new DuplicatedNicknameException();
이 부분은 예외를 처리 하는 부분이 아니여서 이렇게 해당 클래스를 삭제 했습니다

2024-10-14 17:40 UTC, DlrkdhsOff commented on jamanchu/src/main/java/com/recipe/jamanchu/controller/AuthController.java
> +    }
required를 true로 하게 됐을떄 400 Bad Request가 발생이 되지만 따로 전달 되는 메세지가 없어서 required false로 설정을 하였습니다.

2024-10-14 17:57 UTC, heesane commented on jamanchu/src/main/java/com/recipe/jamanchu/controller/AuthController.java
> +    }
넵 확인했습니다!

2024-10-14 17:57 UTC, heesane approved these changes
수고하셨습니다!!

2024-10-15 04:18 UTC, jungheol reviewed
리뷰 드렸습니다. 확인 부탁드려요 ㅎ

2024-10-15 04:18 UTC, jungheol commented on jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
> +  NICKNAME_ALREADY_IN_USE(HttpStatus.OK, "이미 사용 중인 닉내임 입니다."),
닉내임 오타 수정해야 할것 같아요.

2024-10-15 04:18 UTC, jungheol commented on jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
> -    userAccessHandler.existsByNickname(signupDTO.getNickname());
서버단에서는 최종적으로 회원가입 메서드에서는 이메일 중복체크와 닉네임 중복체크 부분을 빼는 것 같은데,
이메일 중복체크 API 와 닉네임 중복체크 API 에서 이미 사용중인 경우에는, 프론트에서 회원가입 버튼이 비활성화 되거나 사용중이지 않은 이메일이나 닉네임으로 수정을 해야만 다음 항목을 입력할 수 있도록 처리가 되는 부분에 대해 이야기가 된걸까요?

2024-10-15 05:06 UTC, DlrkdhsOff commented on jamanchu/src/main/java/com/recipe/jamanchu/model/type/ResultCode.java
> +  NICKNAME_ALREADY_IN_USE(HttpStatus.OK, "이미 사용 중인 닉내임 입니다."),
넵 바로 수정하겠습니다

2024-10-15 05:09 UTC, DlrkdhsOff commented on jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
> -    userAccessHandler.existsByNickname(signupDTO.getNickname());
그 부분은 아직 이야기가 되지 않았습니다..
현재는 중복 확인을 누르고, 사용가능 여부 알림 및 입력란 하단에 추가로 문구가 나오는 방식으로 알고 있습니다.
한얼님께서 말씀하신 부분은 프론트 분들과 한번더 이야기를 해보겠습니다

2024-10-15 05:21 UTC, jungheol commented on jamanchu/src/main/java/com/recipe/jamanchu/service/impl/UserServiceImpl.java
> -    userAccessHandler.existsByNickname(signupDTO.getNickname());
해당 부분에 대한 처리가 되지 않은 상태로, 중복 확인은 했지만 가입 버튼을 누르는게 가능하다면, 현재로는 중복입력이 되어버릴 것 같아서요! 이걸 처리하는 부분은 최종적으로 해당 메서드에 검증 부분을 놔둬야 하는지 논의가 필요해 보이네요~

2024-10-15 06:40 UTC, jungheol approved these changes
프론트에서 확인한 부분 체크했어요!

2024-10-15 06:46 UTC, merged